# Generated by Django 4.1.1 on 2022-09-15 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scheduler',
            new_name='Event',
        ),
    ]
