# Generated by Django 4.1.1 on 2022-09-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0003_day_offer_delete_event"),
    ]

    operations = [
        migrations.DeleteModel(name="Day",),
        migrations.AddField(
            model_name="offer",
            name="Pick_Time",
            field=models.CharField(
                choices=[
                    ("9:30-9:40", "9:30-9:40"),
                    ("9:40-9:50", "9:40-9:50"),
                    ("9:50-9:55", "9:50-9:55"),
                ],
                default="9:30-9:40",
                max_length=9,
            ),
        ),
    ]
